version: "3.6"

services:
  postgres:
    image: "postgres:10-alpine"
    ports:
      - "5432:5432"
    volumes:
      - data_postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  data_postgres:
    driver: local
